# Generated by Django 6.0.6 on 2026-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email address"),
        ),
    ]
