# Generated by Django 6.0.6 on 2026-07-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_teams", models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_day", models.PositiveIntegerField()),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("postponed", "Postponed"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="leagues.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("home_score", models.PositiveIntegerField()),
                ("away_score", models.PositiveIntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="leagues.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="teams", to="leagues.league"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("jersey_number", models.PositiveIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[("GK", "Goal Keeper"), ("DEF", "Defender"), ("MID", "Midfielder"), ("FWD", "Forward")],
                        max_length=3,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="leagues.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="away_matches", to="leagues.team"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="home_matches", to="leagues.team"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(fields=("name", "league"), name="unique_team_name_in_league"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["team", "position"], name="player_team_position_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["league", "status"], name="match_league_status_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["league", "match_day"], name="match_league_matchday_idx"),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="different_teams_per_match",
            ),
        ),
    ]
