# Generated by Django 6.0.6 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_match_matchresult_match_different_teams_per_match"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["league", "status"], name="match_league_status_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["league", "match_day"], name="match_league_matchday_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["team", "position"], name="player_team_position_idx"),
        ),
    ]
